// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.1
// source: pb/meeting.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MeetingService_ProcessAudio_FullMethodName    = "/meeting.MeetingService/ProcessAudio"
	MeetingService_GenerateMinutes_FullMethodName = "/meeting.MeetingService/GenerateMinutes"
)

// MeetingServiceClient is the client API for MeetingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeetingServiceClient interface {
	ProcessAudio(ctx context.Context, opts ...grpc.CallOption) (MeetingService_ProcessAudioClient, error)
	GenerateMinutes(ctx context.Context, in *TranscriptRequest, opts ...grpc.CallOption) (*MinutesResponse, error)
}

type meetingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeetingServiceClient(cc grpc.ClientConnInterface) MeetingServiceClient {
	return &meetingServiceClient{cc}
}

func (c *meetingServiceClient) ProcessAudio(ctx context.Context, opts ...grpc.CallOption) (MeetingService_ProcessAudioClient, error) {
	stream, err := c.cc.NewStream(ctx, &MeetingService_ServiceDesc.Streams[0], MeetingService_ProcessAudio_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &meetingServiceProcessAudioClient{stream}
	return x, nil
}

type MeetingService_ProcessAudioClient interface {
	Send(*AudioChunk) error
	Recv() (*TranscriptionResult, error)
	grpc.ClientStream
}

type meetingServiceProcessAudioClient struct {
	grpc.ClientStream
}

func (x *meetingServiceProcessAudioClient) Send(m *AudioChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *meetingServiceProcessAudioClient) Recv() (*TranscriptionResult, error) {
	m := new(TranscriptionResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *meetingServiceClient) GenerateMinutes(ctx context.Context, in *TranscriptRequest, opts ...grpc.CallOption) (*MinutesResponse, error) {
	out := new(MinutesResponse)
	err := c.cc.Invoke(ctx, MeetingService_GenerateMinutes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeetingServiceServer is the server API for MeetingService service.
// All implementations must embed UnimplementedMeetingServiceServer
// for forward compatibility
type MeetingServiceServer interface {
	ProcessAudio(MeetingService_ProcessAudioServer) error
	GenerateMinutes(context.Context, *TranscriptRequest) (*MinutesResponse, error)
	mustEmbedUnimplementedMeetingServiceServer()
}

// UnimplementedMeetingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMeetingServiceServer struct {
}

func (UnimplementedMeetingServiceServer) ProcessAudio(MeetingService_ProcessAudioServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessAudio not implemented")
}
func (UnimplementedMeetingServiceServer) GenerateMinutes(context.Context, *TranscriptRequest) (*MinutesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateMinutes not implemented")
}
func (UnimplementedMeetingServiceServer) mustEmbedUnimplementedMeetingServiceServer() {}

// UnsafeMeetingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeetingServiceServer will
// result in compilation errors.
type UnsafeMeetingServiceServer interface {
	mustEmbedUnimplementedMeetingServiceServer()
}

func RegisterMeetingServiceServer(s grpc.ServiceRegistrar, srv MeetingServiceServer) {
	s.RegisterService(&MeetingService_ServiceDesc, srv)
}

func _MeetingService_ProcessAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MeetingServiceServer).ProcessAudio(&meetingServiceProcessAudioServer{stream})
}

type MeetingService_ProcessAudioServer interface {
	Send(*TranscriptionResult) error
	Recv() (*AudioChunk, error)
	grpc.ServerStream
}

type meetingServiceProcessAudioServer struct {
	grpc.ServerStream
}

func (x *meetingServiceProcessAudioServer) Send(m *TranscriptionResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *meetingServiceProcessAudioServer) Recv() (*AudioChunk, error) {
	m := new(AudioChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MeetingService_GenerateMinutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GenerateMinutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GenerateMinutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GenerateMinutes(ctx, req.(*TranscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeetingService_ServiceDesc is the grpc.ServiceDesc for MeetingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeetingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meeting.MeetingService",
	HandlerType: (*MeetingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateMinutes",
			Handler:    _MeetingService_GenerateMinutes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessAudio",
			Handler:       _MeetingService_ProcessAudio_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/meeting.proto",
}
