# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meeting.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'meeting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmeeting.proto\x12\x07meeting\"@\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\x05\"Z\n\x13TranscriptionResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x0f\n\x07speaker\x18\x04 \x01(\t\";\n\x11TranscriptRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\ntranscript\x18\x02 \x01(\t\"h\n\x0fMinutesResponse\x12\x14\n\x0c\x61\x63tion_items\x18\x01 \x03(\t\x12\x11\n\tdecisions\x18\x02 \x03(\t\x12\x19\n\x11\x64iscussion_points\x18\x03 \x03(\t\x12\x11\n\tsentiment\x18\x04 \x01(\t2\xa0\x01\n\x0eMeetingService\x12\x45\n\x0cProcessAudio\x12\x13.meeting.AudioChunk\x1a\x1c.meeting.TranscriptionResult(\x01\x30\x01\x12G\n\x0fGenerateMinutes\x12\x1a.meeting.TranscriptRequest\x1a\x18.meeting.MinutesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meeting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=26
  _globals['_AUDIOCHUNK']._serialized_end=90
  _globals['_TRANSCRIPTIONRESULT']._serialized_start=92
  _globals['_TRANSCRIPTIONRESULT']._serialized_end=182
  _globals['_TRANSCRIPTREQUEST']._serialized_start=184
  _globals['_TRANSCRIPTREQUEST']._serialized_end=243
  _globals['_MINUTESRESPONSE']._serialized_start=245
  _globals['_MINUTESRESPONSE']._serialized_end=349
  _globals['_MEETINGSERVICE']._serialized_start=352
  _globals['_MEETINGSERVICE']._serialized_end=512
# @@protoc_insertion_point(module_scope)
